# Config file for the oxygen model. Do not alter this file - make a copy called config.yaml or run data_preprocessing.py/pipeline.py to initialise
# a copy with the default settings. Explanations are found in the comments underneath each setting.

# Note: some settings primarily used for testing remain in the Python scripts which can be changed as needed.

# Which model to build:
build_traditional: true
build_neural_network: true
  # Used in the wrapper script to determine which model type to build

general:
  run_number: 1
    # Automatically changed after each model run (either by pipeline.py or standalone script run). 
    # Can be changed to any number without consequence and reset as needed - used just to track runs.
  run_suffix: ''
    # Used alongside run_number to set the model name. Can be modified to any string; it's recommended to use this to describe 
    # the model run, e.g. '400_evals_no_validation'
  validate: True
    # Bool to determine whether to make the Surrey dataset validation-compatible (if False, can ignore ISARIC data). Switch on if validating.
  host: "127.0.0.1"
  port: 8080
    # Host and port for local tracking serverfor MLflow
  training_meta_cols: 0
  validation_meta_cols: 0
  enable_tracking: False
    # If true, will enable the tracking server for MLflow. Set to false if using a VPN service/other restrictions or the code will not run.

feature_engineering:
  day_zero: True
    # Determine whether to filter to day zero samples only. For better results, disable if metadata is being dropped (see below). 
  text_features:
    # The four text-based comma-separated features included in the dataset. Adds information but also high dimensionality. Turn on to include.
    Medication_48hr: True
    Pre-symptoms: True
    Comorbidity: True
    Regular_meds: True
  min_count: 3
    # Minimum count for text features to be included in the dataset. If set to 0, all text features will be included.

data_preprocessing:
  impute: False # Disabled due to computational restrictions but should be set to true. 
    # Determine whether to impute the data or not; if running standalone scripts (not in pipeline.py) this can be switched off for repeat runs
  drop_metadata: False
    # Determine whether to drop the metadata; i.e. only use proteomics data. 
  num_datasets_imputation: 2
  iterations_imputation: 2
  # Note: 2/2 is the maximum I can reliably achieve, but can be changed with access to increased computational resources.
  imputed_data_config: ''
  # Optional term which can be manually (for now) appended to the '[...]_after_imputation.csv' file to indicate the config used for imputation. 
  # If changing validate/day_zero/drop_metadata or any text_features, you can modify the aforementioned file with a suffix and write above to specify which to use.
  # Suggested template: '_V+D-T2B[M-P-C-R-]M+' for validate=True, day_zero=True, drop_metadata=False, and all text features included.

model_building:
  var_threshold: 1e-10
    # Change this to change the threshold for variance filtering
  feature_selection: True
    # Whether to do feature selection or not - applies to all steps (basic training, hyperparameter exploration, and final model training
  basic_training: True
    # Whether to go through the training of basic models to determine the most promising candidates/feature selectors (alternative is to set certain methods below)
  specify_model:
    # If basic_training is disabled, use the model type/feature selector specified here
    # See the output tables of model_building.py for the appropriate format
    model_type: "RandomForestClassifier"
    fs: "SFM_RF"
  feature_selectors:
    RFECV_LR: False # Some of these are temporaily disabled for testing
    RFECV_SVC: False
    RFECV_RF: False
    RFECV_XGB: False
    SFM_LR: True
    SFM_SVC: True
    SFM_RF: True
    SFM_XGB: True
    SFM_LAS: True
    SFS_LR: False
    SFS_LSVC: False
    SFS_XGB: False
    NONE: True
    # Whether to include each feature selector as a possible candidate for basic_training
  models_to_test:
    # Models to test as part of basic_train; determines which will be carried to the tuning stage
    Logistic_regression: True
    SVM: True
    # Currently SVM should be switched off as certain functions will produce incorrect results due to no predict_proba. If using, check the script to see which.
    Random_forest: True
    AdaBoost: True
    Gradient_boosting: True
    XGBoost: True
    KNN: True
  n_models_to_tune: 2
    # The top N models - change this as needed
  max_evals: 1000 # Needs to be tuned TODO
    # Change this as needed
  track_final: true 
    # Whether to copy the model_output to the designated folder for easier browsing - some functions depend on this so it's strongly recommended to leave it on.


# NOTE: currently using pre-existing ML settings. some (eg var threshold, model_choice) could be set individually
# for each model, but for now for unaminity, both models use the same settings.
neural_network:
  batch_size: 32
    # Batch size for training the neural network
  n_epochs: 1000
  nth_epoch: 50
  learning_rate: 5e-4
  early_stopping: False
    # Whether to use early stopping during training. If True, will stop training if validation loss does not improve for a set number of epochs.
  validation_size: 0.15
    # Size of the validation set as a fraction of the training set
  feature_selection:
    # For neural networks, FS is set manually for now. 
    selector: 'NONE'
    # Specify here, see the feature selectors dict in the neural network training script for options
  use_set_search_space: False
    # Whether to use a fixed search space for hyperopt (ie no hyperparameter tuning) - the values can be changed in neural_network.py

